'use client';

import { useState } from 'react';
import { motion } from 'motion/react';
import { Plus, PieChart, List, Settings, LogOut, Share2 } from 'lucide-react';
import { useExpenses } from '@/lib/expense-context';
import ExpenseList from './ExpenseList';
import AddExpenseModal from './AddExpenseModal';
import AnalyticsChart from './AnalyticsChart';
import BudgetCard from './BudgetCard';
import SettingsModal from './SettingsModal';

export default function DashboardView() {
  const { expenses, settings, logout } = useExpenses();
  const [activeTab, setActiveTab] = useState<'overview' | 'transactions'>('overview');
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);

  const totalSpent = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const budgetLeft = settings.budgetLimit - totalSpent;
  const progress = Math.min((totalSpent / settings.budgetLimit) * 100, 100);

  const handleShare = () => {
    const message = `Expense Report:\nTotal Spent: ${settings.currency}${totalSpent}\nBudget Left: ${settings.currency}${budgetLeft}\n\nGenerated by ExpenseFlow`;
    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  };

  return (
    <div className="min-h-screen bg-stone-50 pb-24 md:pb-8">
      {/* Header */}
      <header className="bg-white border-b border-stone-200 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center text-emerald-600">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
              </svg>
            </div>
            <div>
              <h1 className="text-lg font-semibold text-stone-900 leading-tight">ExpenseFlow</h1>
              <p className="text-xs text-stone-500">Welcome back, {settings.name}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={handleShare}
              className="p-2 text-stone-500 hover:bg-stone-100 rounded-lg transition-colors"
              title="Share on WhatsApp"
            >
              <Share2 size={20} />
            </button>
            <button 
              onClick={() => setIsSettingsOpen(true)}
              className="p-2 text-stone-500 hover:bg-stone-100 rounded-lg transition-colors"
            >
              <Settings size={20} />
            </button>
            <button 
              onClick={logout}
              className="p-2 text-stone-500 hover:bg-red-50 hover:text-red-500 rounded-lg transition-colors"
            >
              <LogOut size={20} />
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-6 space-y-6">
        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <BudgetCard 
            totalSpent={totalSpent} 
            budgetLimit={settings.budgetLimit} 
            currency={settings.currency} 
          />
          <div className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm flex flex-col justify-between">
            <div>
              <p className="text-sm text-stone-500 font-medium mb-1">Total Balance</p>
              <h2 className="text-3xl font-bold text-stone-900">
                {settings.currency}{budgetLeft.toLocaleString()}
              </h2>
            </div>
            <div className="mt-4">
              <div className="flex justify-between text-xs text-stone-500 mb-1">
                <span>Monthly Limit</span>
                <span>{Math.round(progress)}% Used</span>
              </div>
              <div className="h-2 bg-stone-100 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                  className={`h-full rounded-full ${progress > 90 ? 'bg-red-500' : 'bg-emerald-500'}`}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-4 border-b border-stone-200">
          <button
            onClick={() => setActiveTab('overview')}
            className={`pb-3 text-sm font-medium transition-colors relative ${
              activeTab === 'overview' ? 'text-stone-900' : 'text-stone-500 hover:text-stone-700'
            }`}
          >
            Overview
            {activeTab === 'overview' && (
              <motion.div layoutId="tab-indicator" className="absolute bottom-0 left-0 right-0 h-0.5 bg-stone-900" />
            )}
          </button>
          <button
            onClick={() => setActiveTab('transactions')}
            className={`pb-3 text-sm font-medium transition-colors relative ${
              activeTab === 'transactions' ? 'text-stone-900' : 'text-stone-500 hover:text-stone-700'
            }`}
          >
            Transactions
            {activeTab === 'transactions' && (
              <motion.div layoutId="tab-indicator" className="absolute bottom-0 left-0 right-0 h-0.5 bg-stone-900" />
            )}
          </button>
        </div>

        {/* Content */}
        <div className="min-h-[400px]">
          {activeTab === 'overview' ? (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="lg:col-span-2">
                <AnalyticsChart expenses={expenses} currency={settings.currency} />
              </div>
              <div className="lg:col-span-1">
                <h3 className="text-lg font-semibold text-stone-900 mb-4">Recent Activity</h3>
                <ExpenseList limit={5} showFilters={false} />
              </div>
            </div>
          ) : (
            <ExpenseList showFilters={true} />
          )}
        </div>
      </main>

      {/* Floating Action Button */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => setIsAddModalOpen(true)}
        className="fixed bottom-6 right-6 md:bottom-8 md:right-8 w-14 h-14 bg-stone-900 text-white rounded-full shadow-lg shadow-stone-900/20 flex items-center justify-center z-20"
      >
        <Plus size={24} />
      </motion.button>

      {/* Modals */}
      {isAddModalOpen && <AddExpenseModal onClose={() => setIsAddModalOpen(false)} />}
      {isSettingsOpen && <SettingsModal onClose={() => setIsSettingsOpen(false)} />}
    </div>
  );
}
